### ISSUE TITLE
Project is out of date

### ISSUE THREAD

**Issue by maherhanafi** [dlew/android-movies-demo#2]
Hi @dlew,
I updated this project to work with the latest Android Studio 3.x and support Android API 28.
Can you please take a look at this PR:
https://github.com/dlew/android-movies-demo/pull/1

Thanks
Maher

**Comment by dlew** [comment]
I appreciate you looking into this, but frankly this is a 5-year-old demo and I'm not going to put any time into maintaining it. The examples in it are out-of-date and there are better methods to solve these problems now.

You are more than welcome to fork it and carry it on if you want, but I'm not going to be accepting PRs for it anymore.

**Comment by maherhanafi** [comment]
@dlew Fair enough. Thanks
